version: '3'

services:
    web:
        build: .
        command: npm run prod
        environment: 
            - PORT=${PORT}
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - SECRET_KEY=${SECRET_KEY}
            - MAP_API_KEY=${MAP_API_KEY}
        ports:
            - "${PORT}:${PORT}"
        restart: unless-stopped
